// The honest data-source chip.
//
// Every number this product shows comes from one of five places, and the jury is entitled
// to know which without reading a README. `GET /api/v1/meta/provenance` is the authority;
// this component is how a single field says the same thing inline.
//
// The sandbox distinction matters: IDBI's Atlas sandbox answers real endpoints with one
// canned blob shared across APIs, so "we called the bank's API" and "these are the bank's
// numbers" are different claims. BANK_API+sandbox_fixture says the first without the second.
//
// A third distinction rides beside it: a night the sandbox call failed, this platform can
// serve the last good answer that same request got on an earlier night
// (`app/atlas/lastgood.py`). The bytes are still the bank's — the contract's provenance
// enum stays closed at BANK_API|SIMULATED|FIXTURE and never gains a fourth value — but the
// screen owes the reader the fact that tonight's call did not happen. BANK_API_CACHED is
// this component's own vocabulary for that case, never a value the wire sends.

import { useId, useState } from 'react'
import { Beaker, CircleSlash, Database, FlaskConical, History, Landmark } from 'lucide-react'

export const SOURCE = {
  BANK_API: 'BANK_API',
  BANK_API_SANDBOX: 'BANK_API+sandbox_fixture',
  BANK_API_CACHED: 'BANK_API+cached',
  SIMULATED: 'SIMULATED',
  FIXTURE: 'FIXTURE',
  NOT_COLLECTED: 'NOT_COLLECTED',
}

export const SOURCES = {
  [SOURCE.BANK_API]: {
    label: 'Bank API',
    icon: Landmark,
    className: 'bg-idbi-green/10 text-idbi-green border-idbi-green/30',
    description: 'Live from an IDBI Atlas API. The values are the bank’s own.',
  },
  [SOURCE.BANK_API_SANDBOX]: {
    label: 'Bank API · sandbox',
    icon: Beaker,
    className: 'bg-idbi-green/10 text-idbi-green border-idbi-green/30',
    description:
      'Fetched from a real IDBI Atlas endpoint, but the sandbox returns canned data shared across APIs. The call and the shape are real; the values are not the bank’s production numbers.',
  },
  [SOURCE.BANK_API_CACHED]: {
    label: 'Bank API · last good pull',
    icon: History,
    className: 'bg-idbi-green/10 text-idbi-green border-idbi-green/30',
    description:
      'The call tonight failed, so this is the last good response IDBI Atlas gave for the same request. The bytes are the bank’s; they are not from tonight’s run.',
  },
  [SOURCE.SIMULATED]: {
    label: 'Simulated',
    icon: FlaskConical,
    className: 'bg-violet-50 text-violet-700 border-violet-200',
    description:
      'Generated by our synthetic data model, because no bank API supplies this field. Documented in DATA_CARD.md.',
  },
  [SOURCE.FIXTURE]: {
    label: 'Fixture',
    icon: Database,
    className: 'bg-amber-50 text-rag-ambertx border-amber-200',
    description:
      'A recorded response replayed from disk — used while the API subscription is pending approval or the endpoint is unreachable.',
  },
  [SOURCE.NOT_COLLECTED]: {
    label: 'Not collected',
    icon: CircleSlash,
    className: 'bg-slate-100 text-slate-600 border-slate-200',
    description:
      'Deliberately not collected. Nothing shown here was inferred from data the bank does not hold about this customer.',
  },
}

/**
 * Accepts `('BANK_API', {sandbox:true})`, `'BANK_API+sandbox_fixture'`, `'BANK_API+cached'`,
 * or lower case. `cached` wins over `sandbox` when both are set: a reused answer is the
 * more specific — and more recent — disclosure.
 */
export function normaliseSource(value, sandbox = false, cached = false) {
  const raw = String(value ?? '').trim()
  if (!raw) return SOURCE.NOT_COLLECTED
  const upper = raw.toUpperCase().replace(/\s+/g, '')
  if (upper === 'BANK_API+CACHED' || upper === 'BANK_API_CACHED') return SOURCE.BANK_API_CACHED
  if (upper === 'BANK_API+SANDBOX_FIXTURE' || upper === 'BANK_API_SANDBOX') return SOURCE.BANK_API_SANDBOX
  if (upper === 'BANK_API') return cached ? SOURCE.BANK_API_CACHED : sandbox ? SOURCE.BANK_API_SANDBOX : SOURCE.BANK_API
  if (upper === 'SIMULATED') return SOURCE.SIMULATED
  if (upper === 'FIXTURE') return SOURCE.FIXTURE
  if (upper === 'NOT_COLLECTED' || upper === 'NOTCOLLECTED') return SOURCE.NOT_COLLECTED
  return SOURCE.NOT_COLLECTED
}

/**
 * @param {string} source   one of SOURCE, or 'BANK_API' with `sandbox` and/or `cached`
 * @param {boolean} sandbox the Atlas sandbox caveat applies
 * @param {boolean} [cached] tonight's call failed; this is a reused last-good answer
 * @param {string} [detail] extra sentence appended to the tooltip (e.g. "API 402, pulled 16 Sep")
 * @param {boolean} [iconOnly] compact form for dense tables
 */
export default function SourceBadge({ source, sandbox = false, cached = false, detail, iconOnly = false, className = '' }) {
  const key = normaliseSource(source, sandbox, cached)
  const spec = SOURCES[key]
  const Icon = spec.icon
  const tooltipId = useId()
  const [open, setOpen] = useState(false)
  const text = detail ? `${spec.description} ${detail}` : spec.description

  return (
    <span className={`relative inline-flex ${className}`}>
      <button
        type="button"
        aria-describedby={tooltipId}
        aria-expanded={open}
        onMouseEnter={() => setOpen(true)}
        onMouseLeave={() => setOpen(false)}
        onFocus={() => setOpen(true)}
        onBlur={() => setOpen(false)}
        onClick={() => setOpen((v) => !v)}
        className={`inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide transition focus:outline-none focus-visible:ring-2 focus-visible:ring-idbi-green focus-visible:ring-offset-1 ${spec.className}`}
      >
        <Icon size={11} aria-hidden="true" />
        {iconOnly ? <span className="sr-only">{spec.label}</span> : spec.label}
      </button>
      <span
        role="tooltip"
        id={tooltipId}
        hidden={!open}
        className="absolute left-0 top-full z-50 mt-1 w-64 rounded-lg border border-slate-200 bg-white p-2.5 text-left text-[11px] font-normal normal-case leading-relaxed tracking-normal text-slate-600 shadow-lg"
      >
        <b className="block text-slate-800">{spec.label}</b>
        {text}
      </span>
    </span>
  )
}
