// What badge does a screen wear, given where its numbers came from?
//
// `meta.provenance_mode` on every API envelope says how the published run was built, and
// `SourceBadge` has five vocabularies. This maps one to the other in one place so no two
// screens can disagree about what "fixture" means.

import { SOURCE } from '../components/SourceBadge'

const DETAIL = {
  bank: 'Pulled from the IDBI Atlas sandbox by the batch runner.',
  sandbox: 'Fetched from a real Atlas endpoint; the sandbox returns one canned payload shared across APIs, so the call is real and the values are not the bank’s production numbers.',
  fixture: 'Replayed from data/bank/fixture.json — the recorded shape of the bank’s responses, while the API subscriptions are pending.',
  simulated: 'Generated by our synthetic data model, documented in DATA_CARD.md.',
  snapshot: 'Read from the frozen JSON bundled with this build. There is no backend attached to this page.',
}

/**
 * @param {string} mode  `meta.provenance_mode` (bank | sandbox | fixture | simulated | …)
 * @param {string} kind  'api' | 'snapshot', from the data layer
 */
export function badgeForMode(mode, kind) {
  if (kind === 'snapshot') return { source: SOURCE.SIMULATED, sandbox: false, detail: DETAIL.snapshot }
  switch (String(mode || '').toLowerCase()) {
    case 'bank':
    case 'bank_api':
    case 'live':
      return { source: SOURCE.BANK_API, sandbox: false, detail: DETAIL.bank }
    case 'sandbox':
    case 'sandbox_fixture':
      return { source: SOURCE.BANK_API, sandbox: true, detail: DETAIL.sandbox }
    case 'fixture':
      return { source: SOURCE.FIXTURE, sandbox: false, detail: DETAIL.fixture }
    case 'simulated':
    case 'demo':
      return { source: SOURCE.SIMULATED, sandbox: false, detail: DETAIL.simulated }
    default:
      return { source: SOURCE.NOT_COLLECTED, sandbox: false, detail: 'No published model run said where this came from.' }
  }
}

/** A per-family badge, for the provenance strip on the account and sources screens. */
export function badgeForFamilySource(value, { sandboxFixture = false } = {}) {
  const raw = String(value || '').toUpperCase()
  if (raw === 'BANK_API') return { source: SOURCE.BANK_API, sandbox: sandboxFixture }
  if (raw === 'BANK_API+SANDBOX_FIXTURE') return { source: SOURCE.BANK_API, sandbox: true }
  if (raw === 'SIMULATED') return { source: SOURCE.SIMULATED, sandbox: false }
  if (raw === 'FIXTURE') return { source: SOURCE.FIXTURE, sandbox: false }
  return { source: SOURCE.NOT_COLLECTED, sandbox: false }
}

export { SOURCE }
