"""SD-D7 — render ``sources.yaml`` into the DATA_CARD.md parameter table.

The card needs a complete, accurate listing of every empirical parameter the
generator reads, and hand-transcribing 300+ nodes into a markdown table is
exactly the kind of thing that drifts the moment ``sources.yaml`` changes.
This script does the transcription mechanically instead: it reads the same
``sources.py`` provenance store the generator itself reads, and renders every
node — grouped the way the YAML file is grouped (``meta``, ``book``,
``shared``, then each of the eight portfolios) — as a markdown table with the
value, confidence, a one-line reading of the source and the URL ("none" for
an ``assumed`` node, by ``sources.py``'s own contract).

Usage
-----
    python3 src/data_card_params.py                  # full table to stdout
    python3 src/data_card_params.py --census          # confidence census only
    python3 src/data_card_params.py > docs/params.md  # to embed in DATA_CARD.md

Whenever ``sources.yaml`` changes, re-run this and paste the output over the
parameter-table section of ``DATA_CARD.md`` — the table is generated, not
maintained by hand, which is the whole point.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

SRC = Path(__file__).resolve().parent
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from generator import sources  # noqa: E402  (path shim must run first)

__all__ = ["census", "render_table", "render_full_card_section", "main"]

#: how to group the flat (dotted-path, node) list into sections, in the
#: order the YAML file itself declares them
_TOP_LEVEL_ORDER = ("meta", "book", "shared")


def _short_source(text: str, limit: int = 220) -> str:
    """Collapse a folded YAML block scalar to one table-friendly line."""
    line = " ".join(text.split())
    if len(line) <= limit:
        return line
    cut = line.rfind(" ", 0, limit)
    return line[: cut if cut > 0 else limit].rstrip() + " …"


def _format_value(value: object) -> str:
    text = repr(value) if isinstance(value, str) else str(value)
    text = text.replace("|", "\\|")
    if len(text) > 140:
        text = text[:137] + "..."
    return f"`{text}`"


def census() -> Counter:
    """How many nodes carry each confidence level, book-wide."""
    return Counter(node["confidence"] for _, node in sources.iter_nodes())


def _section(prefix: str) -> list[tuple[str, dict]]:
    return [(path, node) for path, node in sources.iter_nodes() if path == prefix or path.startswith(prefix + ".")]


def _table(nodes: list[tuple[str, dict]]) -> str:
    lines = [
        "| Path | Value | Confidence | Source | URL |",
        "|---|---|---|---|---|",
    ]
    for path, node in nodes:
        url = node["url"]
        url_cell = "—" if url == sources.NO_URL else f"<{url}>"
        lines.append(
            f"| `{path}` | {_format_value(node['value'])} | {node['confidence']} "
            f"| {_short_source(node['source'])} | {url_cell} |"
        )
    return "\n".join(lines)


def render_table() -> str:
    """The full parameter table, grouped by section, as markdown."""
    doc = sources.load()
    parts: list[str] = []

    for top in _TOP_LEVEL_ORDER:
        nodes = _section(top)
        if not nodes:
            continue
        parts.append(f"#### `{top}`\n")
        parts.append(_table(nodes))
        parts.append("")

    parts.append("#### `portfolios`\n")
    for key in doc["portfolios"]:
        code = sources.value(f"portfolios.{key}.contract_code")
        nodes = _section(f"portfolios.{key}")
        parts.append(f"##### `{key}` ({code})\n")
        parts.append(_table(nodes))
        parts.append("")

    return "\n".join(parts)


def render_full_card_section() -> str:
    """The table plus the confidence census, headed, ready to paste into DATA_CARD.md."""
    counts = census()
    total = sum(counts.values())
    census_lines = "\n".join(
        f"- **{level}**: {counts.get(level, 0)} ({counts.get(level, 0) / total:.0%})"
        for level in ("high", "medium", "low", "assumed")
    )
    return (
        f"### Confidence census\n\n"
        f"{total} parameter nodes in `src/generator/sources.yaml`, by confidence:\n\n"
        f"{census_lines}\n\n"
        f"Generated by `python3 src/data_card_params.py` from `src/generator/sources.yaml` "
        f"— re-run it after any change to that file; this table is never hand-edited.\n\n"
        f"### Complete parameter table\n\n"
        f"{render_table()}\n"
    )


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--census", action="store_true", help="print only the confidence census")
    args = parser.parse_args(argv)

    if args.census:
        counts = census()
        total = sum(counts.values())
        for level in ("high", "medium", "low", "assumed"):
            n = counts.get(level, 0)
            print(f"{level:10s} {n:4d}  ({n / total:.1%})")
        print(f"{'total':10s} {total:4d}")
        return

    print(render_full_card_section())


if __name__ == "__main__":
    main()
